# Generated by Django 5.1.7 on 2025-03-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='category_items',
        ),
    ]
